[env:esp32s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.psram = enabled
board_upload.maximum_ram_size = 327680
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DCONFIG_SPIRAM_USE=1
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
monitor_speed = 115200
lib_deps =
    lvgl/lvgl@^8.3.11
build_src_filter = +<*> -<.git/> -<.svn/>
