; ESP32-S3 OBD2 Dashboard — Waveshare ESP32-S3-Touch-LCD-2.1
[platformio]
default_envs = waveshare_lcd_21
core_dir = C:/pio
build_cache_dir = C:/pio-cache

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
    https://github.com/lvgl/lvgl.git#v8.4.0

[common]
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -O2
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -I include
    -I src
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[rgb_lcd]
build_flags =
    -DLV_COLOR_16_SWAP=0

[env:waveshare_lcd_21]
extends = env
board = esp32-s3-devkitc-1
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    ${common.build_flags}
    ${rgb_lcd.build_flags}
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_2_1
    -DLVGL_PORT_AVOID_TEARING_MODE=0
